---
- fail: 
    msg: "Only Debian supported for now"
  when: ansible_distribution != 'Debian'

- name: Install wireguard repo (Debian)
  apt_repository:
    filename: unstable-wireguard
    repo: 'deb http://deb.debian.org/debian/ unstable main'
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: Configure wireguard repo (Debian)
  blockinfile:
    path: /etc/apt/preferences.d/limit-unstable
    create: yes
    block: |-
      Package: *
      Pin: release a=unstable
      Pin-Priority: 150

#- name: Apt upgrade (Debian)
#  apt:
#    name: "*"
#    update_cache: yes
#    state: latest

- name: Install dependencies (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - linux-headers-{{ ansible_kernel }}
    - software-properties-common

- name: Enable net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    reload: yes
    state: present


